# Site settings
name: hackberry
email: email
url: "http://www.hackberry.space"
description: "A blog and a portfolio"
author: "aysenur"
title: "Hackberry's Space"
permalink: pretty
baseurl: /

# social
linkedin:
  username: aysenurkaraaslan

twitter:
  username: aysenurkaraslan
